name: Compile Mod

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Initialize Gradle 8.5
      run:  |
       curl -s "https://get.sdkman.io" | bash
       source "$HOME/.sdkman/bin/sdkman-init.sh"
       sdk install gradle 8.5
       gradle wrapper --gradle-version 8.5
    - name: Make executable
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build --no-daemon
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: endoffset-mod
        path: build/libs/*.jar
